/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apacheprojects.sparkwasm.tools;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.ArrayList;
import java.util.BitSet;
import java.util.Comparator;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;
import java.util.zip.ZipOutputStream;
import org.apache.xbean.asm9.ClassReader;
import org.apache.xbean.asm9.ClassWriter;
import org.apache.xbean.asm9.Opcodes;
import org.apache.xbean.asm9.Type;
import org.apache.xbean.asm9.tree.AbstractInsnNode;
import org.apache.xbean.asm9.tree.ClassNode;
import org.apache.xbean.asm9.tree.IincInsnNode;
import org.apache.xbean.asm9.tree.JumpInsnNode;
import org.apache.xbean.asm9.tree.LookupSwitchInsnNode;
import org.apache.xbean.asm9.tree.MethodNode;
import org.apache.xbean.asm9.tree.TableSwitchInsnNode;
import org.apache.xbean.asm9.tree.TryCatchBlockNode;
import org.apache.xbean.asm9.tree.VarInsnNode;

/**
 * Rewrites JVM methods whose {@code maxLocals} exceeds 255 so that every local variable fits in a
 * single-byte operand, which removes the {@code wide} prefixed instructions from the method body.
 *
 * <p>CheerpJ 4.2 mis-decodes {@code wide} local variable instructions: a method containing them
 * either throws a bogus {@link ClassCastException}/{@link ArrayIndexOutOfBoundsException} with an
 * empty stack trace or spins forever. Spark's classpath contains a handful of such methods, all
 * generated by the Scala compiler from very large pattern matches, and three of them sit directly on
 * the query path (analysis, planning and {@code ScalaUDF}).
 *
 * <p>The rewrite is semantics preserving: it runs a liveness analysis over the method body, builds
 * an interference graph over local variable slots and colours it greedily, so slots that are never
 * live at the same time share a single index. Scala's pattern matches use most of their slots in
 * mutually exclusive branches, so the colouring collapses them far below the 256 slot limit.
 *
 * <p>Usage: {@code WideLocalsPatcher <output.jar> <jarDirectory> [jarToScan...]}. Every jar in the
 * directory forms the classpath used to recompute stack map frames; the optional list restricts
 * which jars are scanned (all of them by default). Only classes that actually needed a rewrite are
 * written to the output jar, which is meant to be placed ahead of the untouched upstream jars on the
 * classpath.
 */
public final class WideLocalsPatcher {

  private static final int SLOT_LIMIT = 255;

  private WideLocalsPatcher() {}

  public static void main(String[] args) throws Exception {
    if (args.length < 2) {
      System.err.println("usage: WideLocalsPatcher <output.jar> <jarDirectory> [jarToScan...]");
      System.exit(2);
    }
    File jarDirectory = new File(args[1]);
    List<File> classpathJars = new ArrayList<>();
    File[] listed = jarDirectory.listFiles();
    if (listed != null) {
      for (File file : listed) {
        if (file.getName().endsWith(".jar")) {
          classpathJars.add(file);
        }
      }
    }
    List<File> inputs = new ArrayList<>();
    if (args.length > 2) {
      for (int i = 2; i < args.length; i++) {
        inputs.add(new File(jarDirectory, args[i]));
      }
    } else {
      inputs.addAll(classpathJars);
    }
    URL[] urls = new URL[classpathJars.size()];
    for (int i = 0; i < classpathJars.size(); i++) {
      urls[i] = classpathJars.get(i).toURI().toURL();
    }
    try (URLClassLoader classpath =
            new URLClassLoader(urls, WideLocalsPatcher.class.getClassLoader());
        ZipOutputStream out = new ZipOutputStream(new FileOutputStream(new File(args[0])))) {
      int patched = 0;
      for (File input : inputs) {
        try (ZipFile zip = new ZipFile(input)) {
          Enumeration<? extends ZipEntry> entries = zip.entries();
          while (entries.hasMoreElements()) {
            ZipEntry entry = entries.nextElement();
            if (entry.isDirectory() || !entry.getName().endsWith(".class")) {
              continue;
            }
            byte[] original = read(zip, entry);
            byte[] rewritten = patchClass(original, classpath);
            if (rewritten != null) {
              out.putNextEntry(new ZipEntry(entry.getName()));
              out.write(rewritten);
              out.closeEntry();
              patched++;
            }
          }
        }
      }
      System.out.println("patched classes: " + patched);
    }
  }

  private static byte[] read(ZipFile zip, ZipEntry entry) throws Exception {
    byte[] buffer = new byte[(int) entry.getSize()];
    try (InputStream in = zip.getInputStream(entry)) {
      int off = 0;
      while (off < buffer.length) {
        int n = in.read(buffer, off, buffer.length - off);
        if (n < 0) {
          break;
        }
        off += n;
      }
    }
    return buffer;
  }

  /** Returns rewritten class bytes, or null when the class contains no wide-locals method. */
  private static byte[] patchClass(byte[] bytes, final ClassLoader classpath) {
    ClassNode node = new ClassNode();
    new ClassReader(bytes).accept(node, ClassReader.SKIP_FRAMES | ClassReader.SKIP_DEBUG);
    boolean changed = false;
    for (MethodNode method : node.methods) {
      if (method.maxLocals <= SLOT_LIMIT || method.instructions.size() == 0) {
        continue;
      }
      int before = method.maxLocals;
      if (!compactLocals(node.name, method)) {
        continue;
      }
      changed = true;
      System.out.println(
          "  "
              + node.name
              + "."
              + method.name
              + " maxLocals "
              + before
              + " -> "
              + method.maxLocals);
    }
    if (!changed) {
      return null;
    }
    ClassWriter writer =
        new ClassWriter(ClassWriter.COMPUTE_FRAMES) {
          @Override
          protected ClassLoader getClassLoader() {
            return classpath;
          }
        };
    node.accept(writer);
    return writer.toByteArray();
  }

  /**
   * Reassigns the local variable slots of a method so that they fit under the wide threshold.
   * Returns false when the method cannot be rewritten, in which case it is left untouched.
   */
  private static boolean compactLocals(String owner, MethodNode method) {
    AbstractInsnNode[] insns = method.instructions.toArray();
    int maxLocals = method.maxLocals;

    int[] slotSize = new int[maxLocals];
    boolean[] used = new boolean[maxLocals];
    for (AbstractInsnNode insn : insns) {
      if (insn.getOpcode() == Opcodes.RET || insn.getOpcode() == Opcodes.JSR) {
        return false;
      }
      int slot = slotOf(insn);
      if (slot < 0) {
        continue;
      }
      used[slot] = true;
      slotSize[slot] = Math.max(slotSize[slot], sizeOf(insn));
    }

    int fixed = firstFreeSlotAfterArguments(method);
    for (int slot = 0; slot < Math.min(fixed, maxLocals); slot++) {
      used[slot] = true;
    }
    // A slot read as a two-slot value while its upper half is used on its own cannot be moved
    // safely, so bail out instead of guessing.
    for (int slot = 0; slot + 1 < maxLocals; slot++) {
      if (slotSize[slot] == 2 && used[slot + 1] && slotSize[slot + 1] > 0 && slot + 1 >= fixed) {
        return false;
      }
    }

    BitSet[] liveIn = liveness(insns, method.tryCatchBlocks, maxLocals);
    boolean[][] interferes = new boolean[maxLocals][];
    for (int i = 0; i < maxLocals; i++) {
      interferes[i] = new boolean[maxLocals];
    }
    for (int i = 0; i < insns.length; i++) {
      BitSet live = liveIn[i];
      for (int a = live.nextSetBit(0); a >= 0; a = live.nextSetBit(a + 1)) {
        for (int b = live.nextSetBit(a + 1); b >= 0; b = live.nextSetBit(b + 1)) {
          interferes[a][b] = true;
          interferes[b][a] = true;
        }
      }
      int def = defOf(insns[i]);
      if (def >= 0) {
        for (int a = live.nextSetBit(0); a >= 0; a = live.nextSetBit(a + 1)) {
          if (a != def) {
            interferes[a][def] = true;
            interferes[def][a] = true;
          }
        }
      }
    }

    int[] colour = new int[maxLocals];
    for (int slot = 0; slot < maxLocals; slot++) {
      colour[slot] = slot < fixed ? slot : -1;
    }

    List<Integer> order = new ArrayList<>();
    for (int slot = fixed; slot < maxLocals; slot++) {
      if (used[slot]) {
        order.add(slot);
      }
    }
    final boolean[][] graph = interferes;
    order.sort(
        Comparator.comparingInt((Integer slot) -> -degree(graph[slot])).thenComparingInt(slot -> slot));

    int highest = fixed;
    for (int slot : order) {
      int size = Math.max(1, slotSize[slot]);
      BitSet blocked = new BitSet();
      for (int other = 0; other < maxLocals; other++) {
        if (other == slot || !interferes[slot][other] || colour[other] < 0) {
          continue;
        }
        blocked.set(colour[other]);
        if (Math.max(1, slotSize[other]) == 2) {
          blocked.set(colour[other] + 1);
        }
      }
      int candidate = 0;
      while (true) {
        boolean free = true;
        for (int k = 0; k < size; k++) {
          if (blocked.get(candidate + k)) {
            free = false;
            break;
          }
        }
        if (free) {
          break;
        }
        candidate++;
      }
      colour[slot] = candidate;
      highest = Math.max(highest, candidate + size);
    }

    if (highest > SLOT_LIMIT) {
      System.out.println("  skipped " + owner + "." + method.name + ": needs " + highest + " slots");
      return false;
    }

    for (AbstractInsnNode insn : insns) {
      if (insn instanceof VarInsnNode) {
        VarInsnNode var = (VarInsnNode) insn;
        var.var = colour[var.var];
      } else if (insn instanceof IincInsnNode) {
        IincInsnNode iinc = (IincInsnNode) insn;
        iinc.var = colour[iinc.var];
      }
    }
    method.localVariables = null;
    method.visibleLocalVariableAnnotations = null;
    method.invisibleLocalVariableAnnotations = null;
    method.maxLocals = highest;
    return true;
  }

  private static int degree(boolean[] row) {
    int n = 0;
    for (boolean edge : row) {
      if (edge) {
        n++;
      }
    }
    return n;
  }

  private static int firstFreeSlotAfterArguments(MethodNode method) {
    int slots = (method.access & Opcodes.ACC_STATIC) == 0 ? 1 : 0;
    for (Type type : Type.getArgumentTypes(method.desc)) {
      slots += type.getSize();
    }
    return slots;
  }

  private static int slotOf(AbstractInsnNode insn) {
    if (insn instanceof VarInsnNode) {
      return ((VarInsnNode) insn).var;
    }
    if (insn instanceof IincInsnNode) {
      return ((IincInsnNode) insn).var;
    }
    return -1;
  }

  private static int sizeOf(AbstractInsnNode insn) {
    switch (insn.getOpcode()) {
      case Opcodes.LLOAD:
      case Opcodes.DLOAD:
      case Opcodes.LSTORE:
      case Opcodes.DSTORE:
        return 2;
      default:
        return 1;
    }
  }

  private static int defOf(AbstractInsnNode insn) {
    switch (insn.getOpcode()) {
      case Opcodes.ISTORE:
      case Opcodes.LSTORE:
      case Opcodes.FSTORE:
      case Opcodes.DSTORE:
      case Opcodes.ASTORE:
        return ((VarInsnNode) insn).var;
      default:
        return -1;
    }
  }

  private static int useOf(AbstractInsnNode insn) {
    switch (insn.getOpcode()) {
      case Opcodes.ILOAD:
      case Opcodes.LLOAD:
      case Opcodes.FLOAD:
      case Opcodes.DLOAD:
      case Opcodes.ALOAD:
        return ((VarInsnNode) insn).var;
      case Opcodes.IINC:
        return ((IincInsnNode) insn).var;
      default:
        return -1;
    }
  }

  /** Backward liveness over local variable slots, returning the live-in set of every instruction. */
  private static BitSet[] liveness(
      AbstractInsnNode[] insns, List<TryCatchBlockNode> handlers, int maxLocals) {
    int n = insns.length;
    Map<AbstractInsnNode, Integer> index = new HashMap<>();
    for (int i = 0; i < n; i++) {
      index.put(insns[i], i);
    }
    List<int[]> successors = new ArrayList<>(n);
    for (int i = 0; i < n; i++) {
      successors.add(successorsOf(insns, i, index));
    }
    // Every instruction inside a protected range can jump to its handler.
    if (handlers != null) {
      for (TryCatchBlockNode handler : handlers) {
        int from = index.get(handler.start);
        int to = index.get(handler.end);
        int target = index.get(handler.handler);
        for (int i = from; i < to; i++) {
          int[] existing = successors.get(i);
          int[] extended = new int[existing.length + 1];
          System.arraycopy(existing, 0, extended, 0, existing.length);
          extended[existing.length] = target;
          successors.set(i, extended);
        }
      }
    }

    BitSet[] liveIn = new BitSet[n];
    BitSet[] liveOut = new BitSet[n];
    for (int i = 0; i < n; i++) {
      liveIn[i] = new BitSet(maxLocals);
      liveOut[i] = new BitSet(maxLocals);
    }
    boolean changed = true;
    while (changed) {
      changed = false;
      for (int i = n - 1; i >= 0; i--) {
        BitSet out = new BitSet(maxLocals);
        for (int successor : successors.get(i)) {
          out.or(liveIn[successor]);
        }
        BitSet in = (BitSet) out.clone();
        int def = defOf(insns[i]);
        if (def >= 0) {
          in.clear(def);
        }
        int use = useOf(insns[i]);
        if (use >= 0) {
          in.set(use);
        }
        if (!in.equals(liveIn[i]) || !out.equals(liveOut[i])) {
          liveIn[i] = in;
          liveOut[i] = out;
          changed = true;
        }
      }
    }
    return liveIn;
  }

  private static int[] successorsOf(
      AbstractInsnNode[] insns, int i, Map<AbstractInsnNode, Integer> index) {
    AbstractInsnNode insn = insns[i];
    int opcode = insn.getOpcode();
    if (insn instanceof TableSwitchInsnNode) {
      TableSwitchInsnNode node = (TableSwitchInsnNode) insn;
      int[] targets = new int[node.labels.size() + 1];
      targets[0] = index.get(node.dflt);
      for (int k = 0; k < node.labels.size(); k++) {
        targets[k + 1] = index.get(node.labels.get(k));
      }
      return targets;
    }
    if (insn instanceof LookupSwitchInsnNode) {
      LookupSwitchInsnNode node = (LookupSwitchInsnNode) insn;
      int[] targets = new int[node.labels.size() + 1];
      targets[0] = index.get(node.dflt);
      for (int k = 0; k < node.labels.size(); k++) {
        targets[k + 1] = index.get(node.labels.get(k));
      }
      return targets;
    }
    if (insn instanceof JumpInsnNode) {
      int target = index.get(((JumpInsnNode) insn).label);
      if (opcode == Opcodes.GOTO) {
        return new int[] {target};
      }
      return i + 1 < insns.length ? new int[] {target, i + 1} : new int[] {target};
    }
    if (opcode >= Opcodes.IRETURN && opcode <= Opcodes.RETURN) {
      return new int[0];
    }
    if (opcode == Opcodes.ATHROW) {
      return new int[0];
    }
    return i + 1 < insns.length ? new int[] {i + 1} : new int[0];
  }
}
