/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apacheprojects.sparkwasm.lambda;

import java.lang.invoke.SerializedLambda;
import java.lang.reflect.Method;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Converts JVM lambdas into ordinary serializable objects.
 *
 * <p>CheerpJ's lambda classes cannot be looked up by {@code ObjectStreamClass} once the JVM has
 * created enough of them, and its {@code LambdaMetafactory} cannot rebuild a {@code
 * SerializedLambda} on the way back in. Spark closures are therefore converted the moment Spark
 * cleans them ({@code SparkContext.clean}, rewritten by {@link
 * org.apacheprojects.sparkwasm.tools.CleanClosurePatcher}), so that everything the scheduler
 * serializes is a named class generated by {@link LambdaAdapterFactory}.
 */
public final class Closures {

  private static final ConcurrentHashMap<Class<?>, Object> WRITE_REPLACE =
      new ConcurrentHashMap<Class<?>, Object>();

  private static final Object NOT_A_LAMBDA = new Object();

  private Closures() {}

  /**
   * Returns an equivalent named-class instance when {@code obj} is a lambda, otherwise {@code obj}.
   * Captured arguments are converted recursively, since a Spark closure often captures others.
   */
  public static Object convert(Object obj) {
    SerializedLambda lambda = capture(obj);
    if (lambda == null) {
      return obj;
    }
    int count = lambda.getCapturedArgCount();
    Object[] captured = new Object[count];
    for (int i = 0; i < count; i++) {
      captured[i] = convert(lambda.getCapturedArg(i));
    }
    try {
      Object adapter =
          LambdaAdapterFactory.create(
              lambda.getFunctionalInterfaceClass(),
              lambda.getFunctionalInterfaceMethodName(),
              lambda.getFunctionalInterfaceMethodSignature(),
              lambda.getImplMethodKind(),
              lambda.getImplClass(),
              lambda.getImplMethodName(),
              lambda.getImplMethodSignature(),
              captured);
      if (LambdaAdapterFactory.DEBUG) {
        System.out.println(
            "LAMBDA convert " + lambda.getImplClass() + "." + lambda.getImplMethodName());
      }
      return adapter;
    } catch (Throwable t) {
      throw new IllegalStateException(
          "cannot rebuild closure " + lambda.getImplClass() + "." + lambda.getImplMethodName(), t);
    }
  }

  /** Returns the {@link SerializedLambda} describing {@code obj}, or {@code null} if not a lambda. */
  static SerializedLambda capture(Object obj) {
    if (obj == null || obj instanceof SerializedLambda) {
      return (SerializedLambda) obj;
    }
    Method writeReplace = writeReplace(obj.getClass());
    if (writeReplace == null) {
      return null;
    }
    Object replacement;
    try {
      replacement = writeReplace.invoke(obj);
    } catch (Exception e) {
      throw new IllegalStateException("cannot capture lambda " + obj.getClass().getName(), e);
    }
    return replacement instanceof SerializedLambda ? (SerializedLambda) replacement : null;
  }

  /** Returns the {@code writeReplace} method of a lambda class, or {@code null} for other classes. */
  private static Method writeReplace(Class<?> type) {
    Object cached = WRITE_REPLACE.get(type);
    if (cached == null) {
      cached = NOT_A_LAMBDA;
      if (type.isSynthetic() && !type.isArray()) {
        try {
          Method method = type.getDeclaredMethod("writeReplace");
          method.setAccessible(true);
          cached = method;
        } catch (NoSuchMethodException e) {
          cached = NOT_A_LAMBDA;
        } catch (RuntimeException e) {
          cached = NOT_A_LAMBDA;
        }
      }
      WRITE_REPLACE.putIfAbsent(type, cached);
    }
    return cached == NOT_A_LAMBDA ? null : (Method) cached;
  }
}
