/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apacheprojects.sparkwasm.lambda;

import java.io.Serializable;
import java.lang.invoke.SerializedLambda;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.concurrent.ConcurrentHashMap;
import org.apache.xbean.asm9.ClassWriter;
import org.apache.xbean.asm9.Opcodes;
import org.apache.xbean.asm9.Type;
import org.apache.xbean.asm9.commons.GeneratorAdapter;

/**
 * Rebuilds a lambda from its {@link SerializedLambda} form without using {@code
 * LambdaMetafactory}.
 *
 * <p>CheerpJ 4.2 can execute {@code invokedynamic} call sites created by the compiler, but an
 * instance produced by calling {@code LambdaMetafactory.altMetafactory} reflectively at runtime --
 * the path {@code scala.runtime.LambdaDeserializer} takes when it rebuilds a serialized Scala lambda
 * -- is unusable: every subsequent operation on it (even {@code getClass()}) throws {@link
 * ArrayIndexOutOfBoundsException}. Spark ships every task closure as a serialized lambda, so nothing
 * can execute without a replacement for that path.
 *
 * <p>This factory generates, for each distinct target method, a small class that implements the
 * functional interface and forwards its single abstract method to the target through reflection. The
 * generated class is defined in the target's own class loader so package-private targets stay
 * reachable, and reflection keeps the generated bytecode independent of the target's signature. A
 * deserialized closure is invoked once per partition, so the reflective hop is not on a hot path.
 */
public final class LambdaAdapterFactory {

  private static final String CLOSURE_DESC =
      "Lorg/apacheprojects/sparkwasm/lambda/SerializedClosure;";

  private static final ConcurrentHashMap<String, Constructor<?>> ADAPTERS =
      new ConcurrentHashMap<String, Constructor<?>>();

  private static final java.util.concurrent.atomic.AtomicInteger COUNTER =
      new java.util.concurrent.atomic.AtomicInteger();

  /** Set {@code -Dsparkwasm.lambda.debug=true} to trace closure capture and rebuild. */
  static final boolean DEBUG = Boolean.getBoolean("sparkwasm.lambda.debug");

  private LambdaAdapterFactory() {}

  /** Entry point patched into {@code scala.runtime.LambdaDeserialize#deserializeLambda}. */
  public static Object create(SerializedLambda lambda) throws Throwable {
    Object[] captured = new Object[lambda.getCapturedArgCount()];
    for (int i = 0; i < captured.length; i++) {
      captured[i] = lambda.getCapturedArg(i);
    }
    return create(
        lambda.getFunctionalInterfaceClass(),
        lambda.getFunctionalInterfaceMethodName(),
        lambda.getFunctionalInterfaceMethodSignature(),
        lambda.getImplMethodKind(),
        lambda.getImplClass(),
        lambda.getImplMethodName(),
        lambda.getImplMethodSignature(),
        captured);
  }

  /**
   * Rebuilds a lambda from the raw fields of a serialized lambda record.
   *
   * <p>Used by the {@link SerializedLambda} entry point, by {@link SerializedClosure} while a Spark
   * closure is being deserialized, and by {@link Closures} when a closure is first cleaned.
   */
  public static Object create(
      String functionalInterfaceClass,
      String functionalInterfaceMethodName,
      String functionalInterfaceMethodSignature,
      int implMethodKind,
      String implClass,
      String implMethodName,
      String implMethodSignature,
      Object[] captured)
      throws Throwable {
    if (DEBUG) {
      System.out.println("LAMBDA create " + implClass + "." + implMethodName);
    }
    String key =
        functionalInterfaceClass
            + '.'
            + functionalInterfaceMethodName
            + functionalInterfaceMethodSignature
            + '|'
            + implMethodKind
            + implClass
            + '.'
            + implMethodName
            + implMethodSignature;
    Constructor<?> ctor = ADAPTERS.get(key);
    if (ctor == null) {
      ctor =
          build(
              functionalInterfaceClass,
              functionalInterfaceMethodName,
              functionalInterfaceMethodSignature,
              implClass,
              implMethodName);
      ADAPTERS.putIfAbsent(key, ctor);
    }
    SerializedClosure closure =
        new SerializedClosure(
            functionalInterfaceClass,
            functionalInterfaceMethodName,
            functionalInterfaceMethodSignature,
            implMethodKind,
            implClass,
            implMethodName,
            implMethodSignature,
            captured);
    return ctor.newInstance(
        target(implClass, implMethodName, implMethodSignature), captured, closure);
  }

  /** Reflective dispatch used by every generated adapter. */
  public static Object invoke(Method method, Object[] captured, Object[] args) throws Throwable {
    boolean instanceTarget = !java.lang.reflect.Modifier.isStatic(method.getModifiers());
    Object receiver = null;
    int skip = 0;
    if (instanceTarget) {
      receiver = captured.length > 0 ? captured[0] : args[0];
      skip = captured.length > 0 ? 1 : -1;
    }
    Object[] all;
    if (skip < 0) {
      all = new Object[args.length - 1];
      System.arraycopy(args, 1, all, 0, all.length);
    } else {
      all = new Object[captured.length - skip + args.length];
      System.arraycopy(captured, skip, all, 0, captured.length - skip);
      System.arraycopy(args, 0, all, captured.length - skip, args.length);
    }
    try {
      return method.invoke(receiver, all);
    } catch (java.lang.reflect.InvocationTargetException e) {
      throw e.getCause() == null ? e : e.getCause();
    }
  }

  private static Method target(String implClass, String implMethodName, String implMethodSignature)
      throws Exception {
    ClassLoader loader = loader();
    Class<?> owner = Class.forName(dotted(implClass), false, loader);
    Type[] paramTypes = Type.getArgumentTypes(implMethodSignature);
    Class<?>[] params = new Class<?>[paramTypes.length];
    for (int i = 0; i < params.length; i++) {
      params[i] = load(paramTypes[i], loader);
    }
    for (Class<?> type = owner; type != null; type = type.getSuperclass()) {
      try {
        Method method = type.getDeclaredMethod(implMethodName, params);
        method.setAccessible(true);
        return method;
      } catch (NoSuchMethodException e) {
        // Inherited or interface default target: keep walking.
      }
    }
    Method method = owner.getMethod(implMethodName, params);
    method.setAccessible(true);
    return method;
  }

  private static Constructor<?> build(
      String iface, String samName, String samDesc, String implClass, String implMethodName)
      throws Exception {
    ClassLoader loader = loader();
    // "anonfun" must not appear in the name: Spark's ClosureCleaner treats such a class as a Scala
    // closure and tries to read its class file, which a generated class does not have.
    String name =
        "org/apacheprojects/sparkwasm/lambda/gen/"
            + implClass.replace('/', '_').replace("anonfun", "fn")
            + "_"
            + implMethodName.replace('<', '_').replace('>', '_').replace("anonfun", "fn")
            + "_"
            + COUNTER.incrementAndGet();

    ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_MAXS);
    cw.visit(
        Opcodes.V1_8,
        Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL | Opcodes.ACC_SUPER,
        name,
        null,
        "java/lang/Object",
        new String[] {iface, "java/io/Serializable"});
    cw.visitField(
        Opcodes.ACC_PRIVATE | Opcodes.ACC_FINAL,
        "target",
        "Ljava/lang/reflect/Method;",
        null,
        null);
    cw.visitField(
        Opcodes.ACC_PRIVATE | Opcodes.ACC_FINAL, "captured", "[Ljava/lang/Object;", null, null);
    cw.visitField(
        Opcodes.ACC_PRIVATE | Opcodes.ACC_FINAL,
        "closure",
        CLOSURE_DESC,
        null,
        null);

    String ctorDesc = "(Ljava/lang/reflect/Method;[Ljava/lang/Object;" + CLOSURE_DESC + ")V";
    GeneratorAdapter ctor =
        new GeneratorAdapter(
            Opcodes.ACC_PUBLIC,
            new org.apache.xbean.asm9.commons.Method("<init>", ctorDesc),
            null,
            null,
            cw);
    ctor.loadThis();
    ctor.invokeConstructor(Type.getObjectType("java/lang/Object"), new org.apache.xbean.asm9.commons.Method("<init>", "()V"));
    ctor.loadThis();
    ctor.loadArg(0);
    ctor.putField(Type.getObjectType(name), "target", Type.getObjectType("java/lang/reflect/Method"));
    ctor.loadThis();
    ctor.loadArg(1);
    ctor.putField(Type.getObjectType(name), "captured", Type.getType("[Ljava/lang/Object;"));
    ctor.loadThis();
    ctor.loadArg(2);
    ctor.putField(Type.getObjectType(name), "closure", Type.getType(CLOSURE_DESC));
    ctor.returnValue();
    ctor.endMethod();

    // Serialize as the closure record: the reflective target field cannot be serialized, and the
    // record rebuilds an equivalent adapter on the way back in.
    GeneratorAdapter replace =
        new GeneratorAdapter(
            Opcodes.ACC_PRIVATE,
            new org.apache.xbean.asm9.commons.Method("writeReplace", "()Ljava/lang/Object;"),
            null,
            null,
            cw);
    replace.loadThis();
    replace.getField(Type.getObjectType(name), "closure", Type.getType(CLOSURE_DESC));
    replace.returnValue();
    replace.endMethod();

    Type[] samArgs = Type.getArgumentTypes(samDesc);
    Type samReturn = Type.getReturnType(samDesc);
    GeneratorAdapter sam =
        new GeneratorAdapter(
            Opcodes.ACC_PUBLIC,
            new org.apache.xbean.asm9.commons.Method(samName, samDesc),
            null,
            null,
            cw);
    sam.loadThis();
    sam.getField(Type.getObjectType(name), "target", Type.getObjectType("java/lang/reflect/Method"));
    sam.loadThis();
    sam.getField(Type.getObjectType(name), "captured", Type.getType("[Ljava/lang/Object;"));
    sam.push(samArgs.length);
    sam.newArray(Type.getObjectType("java/lang/Object"));
    for (int i = 0; i < samArgs.length; i++) {
      sam.dup();
      sam.push(i);
      sam.loadArg(i);
      sam.box(samArgs[i]);
      sam.arrayStore(Type.getObjectType("java/lang/Object"));
    }
    sam.invokeStatic(
        Type.getObjectType("org/apacheprojects/sparkwasm/lambda/LambdaAdapterFactory"),
        new org.apache.xbean.asm9.commons.Method(
            "invoke",
            "(Ljava/lang/reflect/Method;[Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;"));
    if (samReturn.getSort() == Type.VOID) {
      sam.pop();
    } else if (samReturn.getSort() == Type.OBJECT || samReturn.getSort() == Type.ARRAY) {
      sam.checkCast(samReturn);
    } else {
      sam.unbox(samReturn);
    }
    sam.returnValue();
    sam.endMethod();
    cw.visitEnd();

    Class<?> generated = define(loader, dotted(name), cw.toByteArray());
    Constructor<?> c =
        generated.getDeclaredConstructor(Method.class, Object[].class, SerializedClosure.class);
    c.setAccessible(true);
    return c;
  }

  private static ClassLoader loader() {
    ClassLoader loader = Thread.currentThread().getContextClassLoader();
    return loader != null ? loader : LambdaAdapterFactory.class.getClassLoader();
  }

  private static final ConcurrentHashMap<ClassLoader, AdapterLoader> LOADERS =
      new ConcurrentHashMap<ClassLoader, AdapterLoader>();

  private static Class<?> define(ClassLoader parent, String name, byte[] bytes) {
    AdapterLoader loader = LOADERS.get(parent);
    if (loader == null) {
      loader = new AdapterLoader(parent);
      AdapterLoader existing = LOADERS.putIfAbsent(parent, loader);
      if (existing != null) {
        loader = existing;
      }
    }
    return loader.define(name, bytes);
  }

  /** Loader that holds the generated adapters; targets are reached reflectively. */
  private static final class AdapterLoader extends ClassLoader {
    AdapterLoader(ClassLoader parent) {
      super(parent);
    }

    synchronized Class<?> define(String name, byte[] bytes) {
      Class<?> existing = findLoadedClass(name);
      return existing != null ? existing : defineClass(name, bytes, 0, bytes.length);
    }
  }

  private static String dotted(String internalName) {
    return internalName.replace('/', '.');
  }

  private static Class<?> load(Type type, ClassLoader loader) throws ClassNotFoundException {
    switch (type.getSort()) {
      case Type.BOOLEAN:
        return boolean.class;
      case Type.BYTE:
        return byte.class;
      case Type.CHAR:
        return char.class;
      case Type.SHORT:
        return short.class;
      case Type.INT:
        return int.class;
      case Type.LONG:
        return long.class;
      case Type.FLOAT:
        return float.class;
      case Type.DOUBLE:
        return double.class;
      case Type.ARRAY:
        return Class.forName(type.getDescriptor().replace('/', '.'), false, loader);
      default:
        return Class.forName(type.getClassName(), false, loader);
    }
  }

  /** Debug helper: describes a serialized lambda without touching the rebuilt instance. */
  public static String describe(SerializedLambda lambda) {
    return lambda.getImplClass()
        + '.'
        + lambda.getImplMethodName()
        + lambda.getImplMethodSignature()
        + " as "
        + lambda.getFunctionalInterfaceClass()
        + " captured="
        + Arrays.toString(new int[] {lambda.getCapturedArgCount()});
  }
}
