# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""
Turn a bare Pyodide interpreter into a configured, initialised Superset installation.

The metadata database and the "examples" analytics database are both SQLite files in the Emscripten
filesystem: Pyodide ships the ``sqlite3`` module, Superset's own migrations support SQLite, and
``superset/examples/*/data.parquet`` in the wheel means the example data needs no network.  The whole
database is a single file, which is also what makes it cheap to snapshot into IndexedDB.

Everything that would reach out of the tab is turned off in configuration rather than stubbed out:
Celery (so queries run synchronously in the request), the cache backends (in-process ``SimpleCache``),
rate limiting (needs a shared store) and thumbnails (need a browser to drive).
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

HOME = Path("/superset-home")

#: The metadata database, and the analytics database the example datasets live in.  They are separate
#: files because SQLite locks a database for the duration of a write transaction: with both in one
#: file, loading the example tables deadlocks against the open metadata session that is loading them.
METADATA_DB = HOME / "superset.db"
EXAMPLES_DB = HOME / "examples.db"
DATABASES = (METADATA_DB, EXAMPLES_DB)

CONFIG_MODULE = "superset_wasm_config"

#: Where the service worker hands requests to this app, and therefore the prefix every URL Superset
#: emits has to carry: ``/superset/`` is the page the visitor loads, so the app lives beside it.
MOUNT = "/_superset"

#: Written next to this package so ``superset.config`` can import it by module name.
CONFIG_SOURCE = f'''
"""Superset configuration for a browser tab.  Generated by superset_wasm.bootstrap."""

SECRET_KEY = "superset-in-the-browser-not-a-secret"
SQLALCHEMY_DATABASE_URI = "sqlite:///{METADATA_DB}"
SQLALCHEMY_EXAMPLES_URI = "sqlite:///{EXAMPLES_DB}"
SQLALCHEMY_TRACK_MODIFICATIONS = False

# SQLite is normally refused as an analytics database because a server-side Superset can read the
# filesystem it shares with other tenants.  Here it is the only database there is, and the
# "filesystem" is this tab's private Emscripten heap.
PREVENT_UNSAFE_DB_CONNECTIONS = False

# No Redis, no memcached, no second process: every cache is a dict in this interpreter.
CACHE_CONFIG = {{"CACHE_TYPE": "SimpleCache", "CACHE_DEFAULT_TIMEOUT": 60 * 60 * 24}}
DATA_CACHE_CONFIG = CACHE_CONFIG
FILTER_STATE_CACHE_CONFIG = {{**CACHE_CONFIG, "CACHE_KEY_PREFIX": "superset_filter_"}}
EXPLORE_FORM_DATA_CACHE_CONFIG = {{**CACHE_CONFIG, "CACHE_KEY_PREFIX": "superset_form_"}}

# Celery would need a broker and a worker process; with async queries off, SQL Lab runs the query in
# the request that submitted it.
CELERY_CONFIG = None
RESULTS_BACKEND = None

# Flask-Limiter's default in-memory store logs a warning on every boot and buys nothing when the
# "client" is the tab itself.
RATELIMIT_ENABLED = False

# Talisman's CSP would have to allow this page's own inline bootstrap; it protects a server-side
# deployment from other origins, which is not the threat model of a static site.
TALISMAN_ENABLED = False
CONTENT_SECURITY_POLICY_WARNING = False

# The request never leaves the tab, so a CSRF token adds a round trip and no protection.
WTF_CSRF_ENABLED = False

FEATURE_FLAGS = {{
    # Thumbnails, alerts and reports all drive a headless browser through Celery.
    "THUMBNAILS": False,
    "ALERT_REPORTS": False,
    "GLOBAL_ASYNC_QUERIES": False,
    "DASHBOARD_VIRTUALIZATION": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
}}

# Long-running queries would need Celery; keep SQL Lab synchronous and honest about it.
SQLLAB_ASYNC_TIME_LIMIT_SEC = 0
SQLLAB_TIMEOUT = 300
SUPERSET_WEBSERVER_TIMEOUT = 300

# Superset is served under a prefix, next to the page that hosts it.  APPLICATION_ROOT reaches the
# frontend in the bootstrap data, where it becomes the React Router basename and the prefix
# SupersetClient puts on every rooted API path; STATIC_ASSETS_PREFIX points the asset tags at the
# copies of the wheel's frontend bundle that this origin serves directly, without going through the
# service worker and the interpreter.
APPLICATION_ROOT = "{MOUNT}"
STATIC_ASSETS_PREFIX = "{MOUNT}"

LOG_LEVEL = "WARNING"
SILENCE_FAB = True
'''


def configure() -> None:
    """Create the Superset home directory and write out the configuration module."""
    HOME.mkdir(parents=True, exist_ok=True)
    config = HOME / f"{CONFIG_MODULE}.py"
    config.write_text(CONFIG_SOURCE)
    os.environ["SUPERSET_HOME"] = str(HOME)
    os.environ["FLASK_APP"] = "superset"
    # ``superset.config`` loads this file over its defaults, by path, at import time.
    os.environ["SUPERSET_CONFIG_PATH"] = str(config)


def create_app() -> Any:
    """Build the real Superset Flask application."""
    from superset.app import create_app as _create_app

    from superset_wasm import shims

    # Needs the Superset modules to exist, so it happens here rather than in ``shims.install()``.
    shims.patch_timeout()
    logging.getLogger("superset").setLevel(logging.WARNING)
    app = _create_app()
    shims.patch_command_timeout()
    return app


def migrate(app: Any) -> None:
    """Run Superset's Alembic migrations -- the same thing ``superset db upgrade`` does."""
    from flask_migrate import upgrade

    with app.app_context():
        upgrade()


def init(app: Any) -> None:
    """Create roles and permissions: the work ``superset init`` does."""
    with app.app_context():
        from superset.extensions import security_manager

        app.appbuilder.add_permissions(update_perms=True)
        security_manager.sync_role_definitions()


def create_admin(app: Any, username: str = "admin", password: str = "admin") -> bool:
    """Create the admin account the visitor logs in with.  Returns True if it was created."""
    with app.app_context():
        from superset.extensions import db, security_manager

        if security_manager.find_user(username):
            return False
        security_manager.add_user(
            username,
            "Superset",
            "Admin",
            f"{username}@superset.invalid",
            security_manager.find_role("Admin"),
            password=password,
        )
        db.session.commit()
        return True


def load_examples(app: Any) -> dict[str, int]:
    """
    Load the example datasets, charts and dashboards that ship inside the wheel.

    ``load_examples_run`` reads ``superset/examples/<name>/data.parquet`` from the installed package
    (``examples://`` resolves to a ``file://`` URL) and imports the YAML chart and dashboard configs
    next to it, so this is entirely local -- no download of example data.
    """
    from superset.cli.examples import load_examples_run

    with app.app_context():
        from superset.extensions import db

        load_examples_run()
        db.session.commit()
    return counts(app)


def counts(app: Any) -> dict[str, int]:
    """How much there is to look at: datasets, charts and dashboards in the metadata database."""
    with app.app_context():
        from superset.connectors.sqla.models import SqlaTable
        from superset.extensions import db
        from superset.models.dashboard import Dashboard
        from superset.models.slice import Slice

        return {
            "datasets": db.session.query(SqlaTable).count(),
            "charts": db.session.query(Slice).count(),
            "dashboards": db.session.query(Dashboard).count(),
        }


def first_dashboard(app: Any) -> str | None:
    """The URL of a dashboard to open, so the visitor lands on something worth looking at."""
    with app.app_context():
        from superset.extensions import db
        from superset.models.dashboard import Dashboard

        dashboard = (
            db.session.query(Dashboard)
            .filter(Dashboard.dashboard_title == "Sales Dashboard")
            .first()
            or db.session.query(Dashboard).first()
        )
        return dashboard.url if dashboard else None


def snapshot() -> dict[str, bytes]:
    """Both database files as bytes, for the page to keep in IndexedDB."""
    return {path.name: path.read_bytes() for path in DATABASES if path.exists()}


def restore(files: dict[str, bytes]) -> bool:
    """Write a snapshot back before the app is created.  Returns True if there was one."""
    if not files:
        return False
    HOME.mkdir(parents=True, exist_ok=True)
    for name, data in files.items():
        (HOME / name).write_bytes(bytes(data))
    return METADATA_DB.exists()
